#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     driveR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,      ,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    ramp,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    wingR,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    wingL,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    block,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "advjoystickdriver1.h"  //Include file to "handle" the Bluetooth messages.

task main(){

	bool button_press = false;
	//bool spinner_adjusted = false;

	//servo[spinnerA] = 126;
	servo[block] = 0;

	waitForStart();

	while(true){

		updateJoystick();

		if (joy1.hat != kHatCentered){

			if(button_press == false){
				button_press = true;
				time1[T1] = 0;
			}

			if(joy1.hat == kHatUp){
				if(time1[T1] <= 25){
	   			motor[driveL] = ((time1[T1] / 25) * 100);
	    		motor[driveR] = ((time1[T1] / 25) * 100);
	    	}
	    	if(time1[T1] > 25){
	    		motor[driveL] = 100;
	    		motor[driveR] = 100;
	    	}
			}

	  	if(joy1.hat == kHatDown){
				if(time1[T1] <= 25){
	   			motor[driveL] = -((time1[T1] / 25) * 100);
	    		motor[driveR] = -((time1[T1] / 25) * 100);
	    	}
	    	if(time1[T1] > 25){
	    		motor[driveL] = -100;
	    		motor[driveR] = -100;
	    	}
	  	}

	  	if(joy1.hat == kHatLeft){
				if(time1[T1] <= 25){
	   			motor[driveL] = -((time1[T1] / 25) * 100);
	    		motor[driveR] = ((time1[T1] / 25) * 100);
	    	}
	    	if(time1[T1] > 25){
	    		motor[driveL] = -100;
	    		motor[driveR] = 100;
	    	}
			}

    	if(joy1.hat == kHatRight){
				if(time1[T1] <= 25){
	   			motor[driveL] = ((time1[T1] / 25) * 100);
	    		motor[driveR] = -((time1[T1] / 25) * 100);
	    	}
	    	if(time1[T1] > 25){
	    		motor[driveL] = 100;
	    		motor[driveR] = -100;
	    	}
	  	}
		}
		else if(joy1.hat == kHatCentered){
			button_press = false;
		 	motor[driveL] = 0;
		 	motor[driveR] = 0;
		}

		if(joy2Hold(6)){
			motor[lift] = 100;
		}
		else if(joy2Hold(8)){
			motor[lift] = -100;
		}
		else{
			motor[lift] = 0;
		}

		if(joy2Hold(5)){
			servo[ramp] = 255;
		}
		else if(joy2Hold(7)){
			servo[ramp] = 0;
		}
		else{
			servo[ramp] = 126;
		}

		if(joy1Hold(6)){
			motor[spinner] = 100;
		}
		else if(joy1Hold(8)){
			motor[spinner] = -100;
		}

		else if(joy1Hold(5)){
			motor[spinner] = 5;
		}
		else if(joy1Hold(7)){
			motor[spinner] = -5;
		}
		else{
			motor[spinner] = 0;
		}

		/*
		if(joy1Hold(1)){
			if(spinner_adjusted == false){
				servo[spinnerA] += 10;
				spinner_adjusted = true;
			}
		}

		else if(joy1Hold(3)){
			if(spinner_adjusted == false){
				servo[spinnerA] -= 10;
				spinner_adjusted = true;
			}
		}
		else{
			spinner_adjusted = false;
		}
		*/

		if(joy2Hold(1)){
			servo[wingL] = 0;
			servo[wingR] = 255;
		}

		if(joy2Hold(3)){
			servo[wingL] = 255;
			servo[wingR] = 0;
		}

		if(joy1Hold(2)){
			servo[block] = 0;
		}

		if(joy1Hold(4)){
			servo[block] = 100;
		}

	}
}
