#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     driveL,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//driveL runs motor 2
//driveR runs motor 1

#include "advjoystickdriver1.h"

task main(){
	waitForStart();
	while(true){
		updateJoystick();
	/*
		if(joy1Hold(7)){
			motor[motorD] = -100;
		}
	*/
		if(joy1.hat != kHatCentered){
			//if a dpad button is being pressed

			if(joy1.hat == kHatUp){
				//set both driving motors to 100% to drive forward
				motor[driveL] = 100;
				motor[driveR] = 100;

			}

			if (joy1.hat == kHatDown){
				//sets both driving motors to -100% to drive backward
				motor[driveL] = -100;
				motor[driveR] = -100;
			}

			if (joy1.hat == kHatRight){
				//drive right
				motor[driveL] = 100;
				motor[driveR] = -100;
			}

			if (joy1.hat == kHatLeft){
				//drive left
				motor[driveL] = -100;
				motor[driveR] = 100;
			}

		}
		else{
			//the dpad isn't being pressed, so don't drive
			motor[driveL] = 0;
			motor[driveR] = 0;
		}
	}
}
